import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { useState } from 'react';

export function HomePage() {
  const { user, continueAsGuest } = useAuth();
  const navigate = useNavigate();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Micro-Estimator States
  const [drivingDistance, setDrivingDistance] = useState(120); // km/week
  const [dietChoice, setDietChoice] = useState<'meat' | 'mixed' | 'vegetarian' | 'vegan'>('mixed');
  const [heatingType, setHeatingType] = useState<'gas' | 'electric' | 'renewable'>('electric');

  // FAQ Accordion State (index of open question, null if closed)
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  async function handleGuestClick() {
    setError(null);
    setIsSubmitting(true);
    try {
      await continueAsGuest();
      navigate('/dashboard');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not start a guest session');
    } finally {
      setIsSubmitting(false);
    }
  }

  // Calculate rough micro-estimation
  const calculateRoughEmissions = () => {
    // 1 km driving = ~0.18 kg CO2
    const transportAnnually = drivingDistance * 52 * 0.18;

    // Diet rough annual kg CO2e
    const dietFactors = {
      meat: 2500,       // High meat
      mixed: 1700,      // Average mixed
      vegetarian: 1000, // No meat
      vegan: 600        // Completely plant-based
    };
    const dietAnnually = dietFactors[dietChoice];

    // Home heating rough annual kg CO2e
    const heatingFactors = {
      gas: 1800,
      electric: 1200,
      renewable: 200
    };
    const heatingAnnually = heatingFactors[heatingType];

    // Fixed constant for average shopping & waste
    const generalAnnually = 1400;

    return Math.round(transportAnnually + dietAnnually + heatingAnnually + generalAnnually);
  };

  const roughTotalTons = (calculateRoughEmissions() / 1000).toFixed(1);

  const faqs = [
    {
      q: "What is a Carbon Footprint?",
      a: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. The global average carbon footprint for a person is close to 4.7 tons per year, but to avoid a 1.5°C rise in global temperatures, the average personal carbon footprint needs to drop under 2 tons per year by 2050."
    },
    {
      q: "What does 'CO2e' stand for?",
      a: "CO2e stands for 'Carbon Dioxide Equivalent'. Different greenhouse gases (like methane from waste, or nitrous oxide from fertilizers) trap heat at different rates. To simplify calculations, scientists convert all emissions into the equivalent amount of Carbon Dioxide (CO2) based on their Global Warming Potential."
    },
    {
      q: "How can individual actions really make a difference?",
      a: "While systemic change is crucial, individual choices drive demand. For example, shifting to public transit, buying local produce, composting organic waste, and reducing meat consumption collectively reduce carbon outputs. Additionally, tracking your habits makes you an active, informed participant in the green transition."
    },
    {
      q: "How does the GreenTrack persona classification work?",
      a: "Our backend uses a mathematical K-Means clustering algorithm. It analyzes your weekly inputs against a standardized comparison population, groups similar consumption patterns, and matches you with a 'lifestyle persona'. This helps you understand which areas of your daily routine have the highest relative impact."
    }
  ];

  return (
    <div className="flex flex-col gap-16 py-4 md:py-8 max-w-5xl mx-auto">
      {/* Hero Section */}
      <section className="flex flex-col items-center text-center gap-6 px-4">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-brand-50 dark:bg-brand-950/30 border border-brand-100 dark:border-brand-900/40 text-brand-700 dark:text-brand-300 text-xs font-bold uppercase tracking-wider animate-float shadow-sm">
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364-6.364l-.707.707M6.343 17.657l-.707.707m0-12.728l.707.707m12.728 12.728l.707-.707M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
          </svg>
          Understand. Track. Reduce.
        </div>

        <h1 className="text-4xl md:text-6xl font-black text-ink-900 tracking-tight max-w-3xl leading-tight">
          Small steps, big impact. <br />
          <span className="bg-gradient-to-r from-brand-600 to-emerald-500 bg-clip-text text-transparent">
            Track your carbon footprint.
          </span>
        </h1>

        <p className="text-base md:text-lg text-ink-700 max-w-2xl leading-relaxed">
          Your personal carbon footprint measures the total greenhouse gas emissions caused by your direct actions. 
          Discover your impact, set reduction goals, and unlock customized habits to live more sustainably.
        </p>

        {error && (
          <p role="alert" className="rounded-lg bg-rose-50 px-4 py-2.5 text-xs text-rose-700 font-semibold border border-rose-100 max-w-md">
            {error}
          </p>
        )}

        <div className="flex flex-wrap items-center justify-center gap-4 mt-2">
          {user ? (
            <Link
              to="/dashboard"
              className="rounded-xl bg-brand-700 px-6 py-3.5 font-bold text-white shadow-md shadow-brand-100 hover:bg-brand-800 hover:scale-[1.02] transition-all text-sm"
            >
              Go to Dashboard
            </Link>
          ) : (
            <>
              <button
                type="button"
                onClick={handleGuestClick}
                disabled={isSubmitting}
                className="rounded-xl bg-brand-700 px-6 py-3.5 font-bold text-white shadow-md shadow-brand-100 hover:bg-brand-800 hover:scale-[1.02] transition-all text-sm disabled:opacity-60"
              >
                {isSubmitting ? 'Starting Session...' : 'Try instantly as Guest'}
              </button>
              <Link
                to="/login"
                className="rounded-xl border border-slate-300 dark:border-slate-800 bg-transparent px-6 py-3.5 font-bold text-ink-700 dark:text-ink-500 hover:bg-slate-100 dark:hover:bg-slate-800/40 hover:text-brand-700 dark:hover:text-brand-400 hover:border-brand-300 dark:hover:border-brand-800 hover:scale-[1.02] transition-all text-sm shadow-sm"
              >
                Sign In / Register
              </Link>
            </>
          )}
        </div>
      </section>

      {/* Interactive Micro-Estimator Section */}
      <section className="glass-panel rounded-3xl p-6 md:p-10 border border-slate-200/50 shadow-md mx-4 grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
        <div className="flex flex-col gap-5">
          <div>
            <span className="text-[10px] font-bold text-brand-600 uppercase tracking-widest">Instant Calculator</span>
            <h2 className="text-2xl md:text-3xl font-black text-ink-900 tracking-tight mt-1">
              Carbon Quick Estimator
            </h2>
            <p className="text-xs text-ink-700 mt-2 leading-relaxed">
              Use these interactive sliders to calculate a quick, rough estimate of your annual carbon footprint. Try modifying the inputs to see how diet, driving, and heating change your impact!
            </p>
          </div>

          {/* Sliders and inputs */}
          <div className="flex flex-col gap-4">
            {/* Driving distance */}
            <div className="flex flex-col gap-1">
              <div className="flex items-center justify-between text-xs font-bold text-ink-700 uppercase">
                <span>Weekly Driving</span>
                <span className="text-brand-600 font-black">{drivingDistance} km</span>
              </div>
              <input
                type="range"
                min="0"
                max="500"
                step="10"
                value={drivingDistance}
                onChange={(e) => setDrivingDistance(Number(e.target.value))}
                className="w-full h-1.5 bg-slate-100 dark:bg-slate-800/60 rounded-lg appearance-none cursor-pointer accent-brand-600"
              />
            </div>

            {/* Diet choice */}
            <div className="flex flex-col gap-1.5">
              <span className="text-xs font-bold text-ink-700 uppercase">Diet Preference</span>
              <div className="grid grid-cols-4 gap-1.5">
                {(['meat', 'mixed', 'vegetarian', 'vegan'] as const).map((choice) => (
                  <button
                    key={choice}
                    type="button"
                    onClick={() => setDietChoice(choice)}
                    className={`rounded-lg py-1.5 text-[10px] font-bold uppercase transition-all border ${
                      dietChoice === choice
                        ? 'bg-brand-600 text-white border-brand-600 shadow-sm'
                        : 'border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/30 text-ink-700'
                    }`}
                  >
                    {choice}
                  </button>
                ))}
              </div>
            </div>

            {/* Heating choice */}
            <div className="flex flex-col gap-1.5">
              <span className="text-xs font-bold text-ink-700 uppercase">Home Heating</span>
              <div className="grid grid-cols-3 gap-1.5">
                {(['gas', 'electric', 'renewable'] as const).map((type) => (
                  <button
                    key={type}
                    type="button"
                    onClick={() => setHeatingType(type)}
                    className={`rounded-lg py-1.5 text-[10px] font-bold uppercase transition-all border ${
                      heatingType === type
                        ? 'bg-brand-600 text-white border-brand-600 shadow-sm'
                        : 'border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/30 text-ink-700'
                    }`}
                  >
                    {type}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Display estimate */}
        <div className="flex flex-col items-center justify-center p-6 bg-slate-50/50 dark:bg-slate-900/30 border border-slate-100 dark:border-slate-800/50 rounded-2xl text-center gap-4">
          <div className="text-[10px] font-bold text-ink-500 uppercase tracking-widest">Your Estimated Footprint</div>
          <div className="flex flex-col items-center">
            <span className="text-5xl md:text-6xl font-black text-brand-600 tracking-tighter">
              {roughTotalTons}
            </span>
            <span className="text-xs font-bold text-ink-700 uppercase tracking-wider mt-1">Metric Tons CO2e / Year</span>
          </div>

          <div className="h-px w-full bg-slate-200/50 dark:bg-slate-800/50" />

          {/* Quick context analysis based on result */}
          <div className="text-[11px] text-ink-700 leading-normal px-2">
            {Number(roughTotalTons) < 3.0 ? (
              <span className="text-emerald-600 dark:text-emerald-400 font-bold">🌿 Excellent! You are below the global average and close to the climate safety target (under 2 tons).</span>
            ) : Number(roughTotalTons) < 5.0 ? (
              <span className="text-amber-600 dark:text-amber-400 font-bold">⚠️ Moderate. You are around the global average (~4.7 tons). Try adopting actions to reduce further.</span>
            ) : (
              <span className="text-red-500 dark:text-red-400 font-bold">🚨 High. Your emissions exceed the global average. Setting reduction goals will make a big difference!</span>
            )}
          </div>
        </div>
      </section>

      {/* Did You Know? Facts Banner */}
      <section className="bg-brand-600 text-white rounded-3xl p-8 mx-4 flex flex-col md:flex-row items-center justify-between gap-6 shadow-lg shadow-brand-100/10">
        <div className="flex flex-col gap-2 max-w-xl text-center md:text-left">
          <span className="text-[10px] font-black uppercase tracking-wider text-brand-200">The Climate Challenge</span>
          <h2 className="text-2xl font-black tracking-tight leading-tight">
            Targeting &lt;2.0 Tons by 2050
          </h2>
          <p className="text-xs text-brand-100 leading-relaxed">
            The Intergovernmental Panel on Climate Change (IPCC) states that limiting warming to 1.5°C requires dropping global personal emissions to under 2 tons per year. Currently, average footprints in some developed countries exceed 15 tons.
          </p>
        </div>
        <div className="shrink-0 flex items-center justify-center bg-white/10 px-6 py-4 rounded-2xl border border-white/15">
          <div className="text-center">
            <span className="block text-3xl font-black text-white">4.7t</span>
            <span className="text-[9px] uppercase tracking-wider font-bold text-brand-200">Global Average</span>
          </div>
          <div className="h-8 w-px bg-white/20 mx-6" />
          <div className="text-center">
            <span className="block text-3xl font-black text-amber-300">2.0t</span>
            <span className="text-[9px] uppercase tracking-wider font-bold text-brand-200">IPCC Target</span>
          </div>
        </div>
      </section>

      {/* Carbon Science Deep Dive Section */}
      <section className="grid grid-cols-1 md:grid-cols-2 gap-12 items-start px-4">
        <div className="flex flex-col gap-5">
          <h2 className="text-2xl md:text-3xl font-black text-ink-900 tracking-tight">
            What Drives Your Emissions?
          </h2>
          <p className="text-sm text-ink-700 leading-relaxed">
            Every product we purchase, calorie we consume, and kilometer we travel has a production supply chain. The extraction of raw materials, refining, distribution, and disposal all release greenhouse gases. Here is a scientific look at why our primary tracking areas matter:
          </p>
          <div className="flex flex-col gap-4">
            <div className="flex gap-3">
              <span className="text-emerald-500 font-bold">✓</span>
              <p className="text-xs text-ink-700 leading-relaxed">
                <strong>Transportation:</strong> Fossil fuel cars convert gasoline into CO2 and other particulates. Flying has high heat-trapping indices because emissions are released high in the stratosphere.
              </p>
            </div>
            <div className="flex gap-3">
              <span className="text-emerald-500 font-bold">✓</span>
              <p className="text-xs text-ink-700 leading-relaxed">
                <strong>Food & Agriculture:</strong> Methane (CH4) has a Global Warming Potential 28 times higher than CO2. Ruminant livestock (like beef and sheep) produce high volumes of methane during digestion.
              </p>
            </div>
            <div className="flex gap-3">
              <span className="text-emerald-500 font-bold">✓</span>
              <p className="text-xs text-ink-700 leading-relaxed">
                <strong>Home Electricity:</strong> Burning coal, natural gas, and oil to power appliances releases carbon. Switching to clean energy sources (wind, solar, nuclear) drops grid emissions to near zero.
              </p>
            </div>
          </div>
        </div>

        {/* Detailed Topic Cards */}
        <div className="flex flex-col gap-4">
          <div className="glass-panel p-5 rounded-2xl flex flex-col gap-2">
            <h3 className="font-bold text-sm text-ink-900">⚡ Grid Intensity</h3>
            <p className="text-[11px] text-ink-700 leading-normal">
              Electricity is carbon-tracked using grid emission intensity (measured in kg CO2 per kWh). This factor fluctuates depending on your utility provider's fuel mix (fossil fuels vs. renewables).
            </p>
          </div>
          <div className="glass-panel p-5 rounded-2xl flex flex-col gap-2">
            <h3 className="font-bold text-sm text-ink-900">🍎 Local Food Supply Chains</h3>
            <p className="text-[11px] text-ink-700 leading-normal">
              Food mileage (transport emissions) contributes to carbon, but agricultural production makes up the bulk of food's footprint. Eating plant-based drops footprints more than eating purely local meat.
            </p>
          </div>
          <div className="glass-panel p-5 rounded-2xl flex flex-col gap-2">
            <h3 className="font-bold text-sm text-ink-900">♻️ Methane & Landfills</h3>
            <p className="text-[11px] text-ink-700 leading-normal">
              When food and organic waste decompose in anaerobic landfills (without oxygen), they release methane gas. Composting or reducing food waste diverts materials, avoiding methane generation entirely.
            </p>
          </div>
        </div>
      </section>

      {/* How it Works Flow */}
      <section className="glass-panel rounded-3xl p-8 md:p-12 border border-slate-200/50 shadow-md mx-4">
        <h2 className="text-center text-2xl md:text-3xl font-black text-ink-900 tracking-tight mb-12">
          Start Your Climate Journey
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="flex flex-col items-center text-center gap-3 relative">
            <div className="h-12 w-12 rounded-full bg-brand-100 dark:bg-brand-900/40 text-brand-700 dark:text-brand-300 font-black text-base flex items-center justify-center border border-brand-200 dark:border-brand-800/30">
              1
            </div>
            <h3 className="font-bold text-base text-ink-900">Track</h3>
            <p className="text-xs text-ink-700 leading-relaxed px-4">
              Complete our 5-step wizard calculator to get a highly customized estimation of your annual footprint.
            </p>
          </div>

          <div className="flex flex-col items-center text-center gap-3 relative">
            <div className="h-12 w-12 rounded-full bg-brand-100 dark:bg-brand-900/40 text-brand-700 dark:text-brand-300 font-black text-base flex items-center justify-center border border-brand-200 dark:border-brand-800/30">
              2
            </div>
            <h3 className="font-bold text-base text-ink-900">Analyze</h3>
            <p className="text-xs text-ink-700 leading-relaxed px-4">
              Explore responsive visual breakdown charts, comparative benchmarks, and historical trend trackers.
            </p>
          </div>

          <div className="flex flex-col items-center text-center gap-3 relative">
            <div className="h-12 w-12 rounded-full bg-brand-100 dark:bg-brand-900/40 text-brand-700 dark:text-brand-300 font-black text-base flex items-center justify-center border border-brand-200 dark:border-brand-800/30">
              3
            </div>
            <h3 className="font-bold text-base text-ink-900">Reduce</h3>
            <p className="text-xs text-ink-700 leading-relaxed px-4">
              Pick practical habits from our action library, set custom reduction targets, and watch your total savings accumulate.
            </p>
          </div>
        </div>
      </section>

      {/* Accordion FAQ Section */}
      <section className="flex flex-col gap-6 px-4">
        <h2 className="text-center text-2xl md:text-3xl font-black text-ink-900 tracking-tight">
          Frequently Asked Questions
        </h2>
        <div className="flex flex-col gap-3 max-w-3xl mx-auto w-full">
          {faqs.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <div
                key={idx}
                className="glass-panel rounded-xl overflow-hidden border border-slate-200/60 dark:border-slate-800/40"
              >
                <button
                  type="button"
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  aria-expanded={isOpen}
                  className="w-full text-left px-5 py-4 flex items-center justify-between font-bold text-sm text-ink-900 hover:bg-slate-50 dark:hover:bg-slate-800/20 transition-colors"
                >
                  <span>{faq.q}</span>
                  <span className="text-brand-600 text-lg transition-transform duration-200 select-none">
                    {isOpen ? '−' : '+'}
                  </span>
                </button>
                {isOpen && (
                  <div className="px-5 pb-4 text-xs text-ink-700 leading-relaxed border-t border-slate-100/50 dark:border-slate-850/30 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* Footer Call to Action */}
      <section className="text-center flex flex-col items-center gap-5 px-4 mb-4 select-none">
        <h2 className="text-3xl font-black text-ink-900 tracking-tight">
          Ready to reduce your impact?
        </h2>
        <p className="text-sm text-ink-700 max-w-xl leading-relaxed">
          Join thousands of individuals managing their footprints. Try our calculator without registering, or make a free account to persist your progress.
        </p>
        <button
          type="button"
          onClick={handleGuestClick}
          disabled={isSubmitting}
          className="rounded-xl bg-brand-700 px-8 py-4 font-bold text-white shadow-md shadow-brand-100 hover:bg-brand-800 hover:scale-[1.02] transition-all text-sm disabled:opacity-60 mt-2"
        >
          {isSubmitting ? 'Starting Session...' : 'Start Tracking Now'}
        </button>
      </section>
    </div>
  );
}
